## TASK 1

Question 1

In [1]:
def compute(a,b):
    try:
        res=a/b
    except:
        print("Second argument must be non-zero, Enter a non zero value")
        return compute(a,int(input()))
    else:
        return res

print(compute(3,0))


Second argument must be non-zero, Enter a non zero value
2
1.5


Question 2

In [2]:
subjects=["Americans","Indians"] 
verbs=["Play", "watch"]  
objects=["Baseball","cricket"]

ind_comb=[(i,j,k) for i in (0,1) for j in (0,1) for k in (0,1)]
for i in ind_comb:
    print("{} {} {}.".format(subjects[i[0]], verbs[i[1]],objects[i[2]]))

Americans Play Baseball.
Americans Play cricket.
Americans watch Baseball.
Americans watch cricket.
Indians Play Baseball.
Indians Play cricket.
Indians watch Baseball.
Indians watch cricket.


## TASK 2

Question 1

In [3]:
import numpy as np
x = np.array([1,2,3,4])
N = 4
#print(np.vander(x,N, increasing = True))
#print(np.vander(x,N, increasing = False))
print(np.column_stack([x**(N-i-1) for i in range(N)]))
print(np.column_stack([x**(N-i) for i in range(N,0,-1)]))


[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
